### ISSUE TITLE
Crash while read sms on some devices. 

### ISSUE THREAD

**Issue by abtuhin** [briankabiro/react-native-get-sms-android#20]
I am getting some crashes on some particular device. Here is my crashlytics log : 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
       at com.react.SmsModule.list(Unknown Source)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source)
       at com.facebook.react.bridge.queue.NativeRunnable.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source)
       at android.os.Looper.loop(Looper.java:210)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)
```

a solution or workaround would be a great help. 
Thanks.

**Comment by briankabiro** [comment]
Hi @abtuhin. Let me look into it and I'll get back.

**Comment by abtuhin** [comment]
Here is the log from crashlytics @briankabiro 

![screen shot 2019-02-14 at 12 35 55 pm](https://user-images.githubusercontent.com/13661720/52767744-41862180-2fe0-11e9-8248-5792cdc147b6.png)

**Comment by briankabiro** [comment]
Thanks for sending it over. It appears to be occurring because of a null-pointer exception. The solution would be to check if `Cursor.moveToNext()!=null` before running the code that lists the messages.

**Comment by abtuhin** [comment]
`Cursor.moveToNext()!=null` doesn't applicable. 
i have tried using `while (cursor!=null && cursor.getCount() > 0 && cursor.moveToNext()){...}`
And still getting crashes in firebase log @briankabiro

**Comment by briankabiro** [comment]
Hmm interesting. Same error still?

_Also, apologies. The issue closed automatically after merging the PR_

**Comment by abtuhin** [comment]
Yes, but i couldn't reproduce this using emulator or any devices. But some users are facing this issue that i can see from crashlytics log. Most of the case it's xioami device or oppo device, version 5

**Comment by briankabiro** [comment]
Ok. #21 also lists that there's an issue with getting SMS's on Xiaomi devices. 

I have a hunch that it's because the devices run their custom Android OS and there's something that they have that's causing the error.

**Comment by briankabiro** [comment]
Hey, @abtuhin. 

Have released 1.3.7; is the issue still present?

**Comment by abtuhin** [comment]
Sorry for being late to reply @briankabiro 
I think the issue still exists. This is causing for android version 5 only, some Xioami and OPPO devices

**Comment by mikehardy** [comment]
> I think the issue still exists. 

But we need to know *for sure* one way or the other. [There is a null pointer check in the latest code for the exact object that was null](https://github.com/briankabiro/react-native-get-sms-android/commit/284ff1f1d037b94120acd1331f18918d7af79a87), so I can't understand how it would still happen. It is always possible I am misunderstanding but I would want to know for sure that it is happening after integrating the latest release before spending time on it...

**Comment by SmirnovM91** [comment]
Do you have any ideas how to fix it?
I have the same errors
