### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'myPath/strings.xml

### ISSUE THREAD

**Issue by devcer** [briankabiro/react-native-get-sms-android#64]
I'm new to React-Native and I tried to use this package but I see the following error. Any thoughts on How I could fix this? 

I see the path it is trying to resolve is incorrect

My path: SmsReader/android/app/src/main/res/values/strings.xml
Path it is trying to resolve: SmsReader/android/src/main/res/values/strings.xml

Here goes the complete log

error Linking "react-native-get-sms-android" failed.
Error: ENOENT: no such file or directory, open '/Users/santoshv/Documents/projects/SmsReader/android/src/main/res/values/strings.xml'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at applyPatch (/Users/santoshv/Documents/projects/SmsReader/node_modules/@react-native-community/cli-platform-android/build/link/patches/applyPatch.js:42:51)
    at Object.registerNativeAndroidModule [as register] (/Users/santoshv/Documents/projects/SmsReader/node_modules/@react-native-community/cli-platform-android/build/link/registerNativeModule.js:33:27)
    at /Users/santoshv/Documents/projects/SmsReader/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:63:16
    at Array.forEach (<anonymous>)
    at linkDependency (/Users/santoshv/Documents/projects/SmsReader/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:36:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.link [as func] (/Users/santoshv/Documents/projects/SmsReader/node_modules/@react-native-community/cli/build/commands/link/link.js:110:5)
    at async Command.handleAction (/Users/santoshv/Documents/projects/SmsReader/node_modules/@react-native-community/cli/build/index.js:186:9)

**Comment by briankabiro** [comment]
Hey. Welcome to the club!

Did you run `react-native link react-native-get-sms-android`?
